author = Artur Tarassow
email = atecon@posteo.de
version = 0.3
date = 2021-09-20
description = Collection of tools for handling panel data
tags = C10
min-version = 2021a
public = pcum pquantile pxfraction pfirst plast pmode pxmean panelinfo ppolyfit mpmean fe_estimator pols_estimator panel_predict meanc_robust sdc_robust
help = PanelTools_help.txt
sample-script = PanelTools_sample.inp
depends = extra
data-requirement = needs-panel-data
