author = Artur Tarassow
email = atecon@posteo.de
version = 0.2
date = 2021-07-22
description = Collection of tools for handling panel data
tags = C10
min-version = 2021a
public = pcum pquantile pxfraction pfirst plast pmode pxmean panelinfo ppolyfit
help = PanelTools_help.txt
sample-script = PanelTools_sample.inp
depends = extra
data-requirement = needs-panel-data