author = Artur Tarassow
email = atecon@posteo.de
version = 0.1
date = 2021-07-13
description = Collection of tools for handling panel data
tags = C10
min-version = 2021a
public = pcum pquantile pxfraction pfirst plast pmode pxmean panelinfo
help = PanelTools_help.txt
sample-script = PanelTools_sample.inp
depends = extra